### ISSUE TITLE
Missing Liang Yue image in Summon Tracker

### ISSUE THREAD

**Issue by Zari0t** [windbow27/kornblume#125]
![Image](https://github.com/user-attachments/assets/023deca2-ab6d-4418-b335-a92d2e3d27cd)

It's the only image of hers on the entire app that's missing. Probably just a naming issue (_Liang_ vs _Liang Yue_).

**Comment by windbow27** [comment]
fixed

**Comment by Zari0t** [comment]
Actually not fixed, sorry to say.

Apparently it's _not_ a naming issue, but rather the app is attempting to fetch this image by its name, rather than her charID, and is doing it from the items directory. Using inspect element...
`<div class="w-10 rounded bg-orange-300">`
    `    <img src="images/items/common/Liang.webp" alt="Liang">`
`</div>`

**Comment by windbow27** [comment]
btw the app fetchs by name, because the pull image itself doesn't provide id. if the name isn't found, the fallback is the special icon (used in thread banner if you remember lol)
![Image](https://github.com/user-attachments/assets/b9c805d6-f6af-4286-a952-7318972000c4)
